---
title: "Portfolio 10"
author: "Anders, Gustav H, Morten & Sigrid"
date: "4/29/2020"
output: html_document
---

```{r setup, include=FALSE}
pacman::p_load(tidyverse, GPArotatio, mvtnorm, polycor, psych,corpcor,GPArotation,psych,pastecs)

df <- read_csv("emp_all_all.csv")
?read_csv()
```

# Portfolio 10

## inspecting the data - covariance matrix
```{r}

#correlation
df_cor <- cor(df,use='complete.obs')
df_cor <-round(df_cor,3)
df_cor
corrgram(df_cor, col.regions =  colorRampPalette(c("dodgerblue4", 'dodgerblue','white', 'gold',"firebrick4")),cor.method='pearson')

# ANOTHER WAY OF DOING THE SAME THING:

# numeric covariates
cov(df)
# figure corrgram
library(corrgram)
corrgram(df, col.regions =  colorRampPalette(c("dodgerblue4", 'dodgerblue','white', 'gold',"firebrick4")),cor.method='pearson')

# determinant - very small 
det(cor(df))

####### PCA analysis

df_pca <-princomp(df[,1:2])
matplot(df_pca$scores[,1],df_pca$scores[,2],type='p',pch=16, col=1,xlab = 'score comp1', ylab = 'score comp2')
view(matplot)

#Get variance measures
summary(df_pca)
#Get loadings
df_pca$loadings

## PCA ANALYSIS - works better??
df_prcomp<-prcomp(df,scale=TRUE)
df_prcomp$rotation

image(t(abs(df_prcomp$rotation[7:1,])),axes=FALSE,col=heat.colors(50))

#scree plot
plot(df_prcomp$sdev)

#continuing with the first four PC's

#Find means for variables to see if they differ
# eigen()


```

